# Generated by Django 4.2 on 2024-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
