# Generated by Django 4.2 on 2024-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
