# Generated by Django 4.2.19 on 2025-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pagecontent_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_type',
            field=models.CharField(choices=[('Become a Drop Shipper', 'Become a Drop Shipper'), ('Promo & Deals', 'Promo & Deals'), ('Get to know Us', 'Get to know Us'), ('For Consumers', 'For Consumers')], max_length=255),
        ),
    ]
