# Generated by Django 4.2 on 2025-01-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='title',
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('bio', models.TextField(blank=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_figures', to='core.aboutus')),
            ],
        ),
    ]
