# Generated by Django 4.2 on 2025-01-10 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutus_remove_contactinquiry_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
